language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  - sudo apt-get install -y libclang1
  - sudo ln -s /usr/lib/llvm-3.4/lib/libclang.so.1 /usr/lib/libclang.so

script:
  - ./deploy.sh
