language: cpp

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_4567f3d26443_key -iv $encrypted_4567f3d26443_iv -in deploy_key.enc -out deploy_key -d
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386

script:
  - ./deply.sh
