language: cpp

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  - sudo apt-get install python3.6 python3.6-dev

script:
  - ./deploy.sh
