language: cpp

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  - sudo apt-get install python3 python3-dev

script:
  - ./deploy.sh
