language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  - sudo apt-get install -y libclang-3.9-dev
  - find /usr/lib -type f -name 'libclang*.so*'
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libclang-3.9.so.1 /usr/lib/libclang.so

script:
  - ./deploy.sh
