language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  - sudo apt-get install -y clang

script:
  - ./deploy.sh
